### ISSUE TITLE
Juci under MSYS2 doesnt appear to run

### ISSUE THREAD

**Issue by AndyPage3** [cppit/jucipp#289]
The latest version of Juci compiles but when i run the exe it finishes straight away with no indication what is wrong. If i run it through gdb i get this error : During startup program exited with code 0xc0000139 .

**Comment by eidheim** [comment]
See #269, and there is a fix in https://github.com/Alexpux/MINGW-packages/issues/1685 but I have not tried it. The problem lies in the latest gtk-related packages.

**Comment by eidheim** [comment]
@d3rrial did you manage to run juCi++ on MSYS2 during the last week?

**Comment by d3rrial** [comment]
No, unfortunately not. I couldn't downgrade gtk in MSYS2. I'll just wait until they release an official update in pacman.

**Comment by d3rrial** [comment]
After the latest update of GTK on MSYS it still does not work for me. Error codes 127 and 139 for me.

**Comment by eidheim** [comment]
The solution is to rebuild mingw-w64-gtksourceviewmm3.

**Comment by eidheim** [comment]
For future reference, here is how you rebuild gtksourceviewmm3:
```sh
git clone git://github.com/Alexpux/MINGW-packages
cd MINGW-packages/mingw-w64-gtksourceviewmm3
makepkg-mingw -sLf
```

Then, install the new gtksourceviewmm3 package:
```sh
pacman -U mingw-w64-x86_64-gtksourceviewmm3*
```

**Comment by Darksider3** [comment]
@eidheim I would suggest to write that down in an INSTALL.md/install_msys.md/Wikipage.. It is simpler, i think.

**Comment by eidheim** [comment]
@Darksider3 was hoping this issue would be resolved by now. But we might have to do this yes.

**Comment by eidheim** [comment]
I've given up waiting for a gtksourceviewmm3 rebuild on MSYS2, and instead updated the installation instructions for MSYS2 to include the fix above (https://github.com/cppit/jucipp/issues/289#issuecomment-278352173).

**Comment by DREAMWORLDVOID** [comment]
Well, I encountered the same problem today when trying to run jucipp built with the latest Msys2 packages. I personally suggest that it should be documented since it looks like the problem won't be fixed in a while.

**Comment by eidheim** [comment]
Did you upgrade your system? This issue was fixed a while ago, but I forgot to close it

**Comment by DREAMWORLDVOID** [comment]
@eidheim Now i did finish updating the system. The program compiles and runs, but it gets stuck whenever I try to type a letter into it.

**Comment by eidheim** [comment]
@DREAMWORLDVOID Thank you, but I am not able to reproduce this issue. Maybe try do a full recompilation of juCi++ after upgrading MSYS2?

**Comment by DREAMWORLDVOID** [comment]
@eidheim Rebuilt with MinGW-w64-x86_64 toolchain and still get stucked. I guess something in the toolchain might went wrong or does not support my operating system(win10 1709).
